import type { AliasLevel } from '~/types'

/**
 * Слова Alias на английском: собираются отдельно, а не переводом русских. Существительное в единственном числе,
 * со строчной буквы, ≤ 24 символов. Словосочетания — только устойчивые. Внутри языка слово не повторяется, в том числе между уровнями.
 */
export default {
  easy: [
    'cat',
    'dog',
    'ball',
    'apple',
    'house',
    'sun',
    'car',
    'fish',
    'book',
    'table',
    'spoon',
    'bird',
    'flower',
    'tree',
    'milk',
    'cake',
    'hat',
    'umbrella',
    'train',
    'airplane',
    'horse',
    'giraffe',
    'banana',
    'clock',
    'bed',
    'star',
    'snowman',
    'bicycle',
    'ice cream',
    'butterfly',
    'moon',
    'rain',
    'snow',
    'cloud',
    'rainbow',
    'puppy',
    'kitten',
    'cow',
    'pig',
    'sheep',
    'goat',
    'duck',
    'chicken',
    'rabbit',
    'mouse',
    'frog',
    'turtle',
    'snail',
    'bee',
    'ant',
    'spider',
    'ladybug',
    'caterpillar',
    'worm',
    'owl',
    'parrot',
    'penguin',
    'lion',
    'tiger',
    'bear',
    'elephant',
    'monkey',
    'zebra',
    'hippo',
    'crocodile',
    'snake',
    'kangaroo',
    'koala',
    'panda',
    'fox',
    'wolf',
    'deer',
    'squirrel',
    'hedgehog',
    'camel',
    'dolphin',
    'whale',
    'shark',
    'octopus',
    'crab',
    'jellyfish',
    'starfish',
    'seal',
    'dinosaur',
    'dragon',
    'unicorn',
    'mermaid',
    'ghost',
    'robot',
    'princess',
    'king',
    'queen',
    'clown',
    'fairy',
    'teddy bear',
    'doll',
    'toy',
    'kite',
    'balloon',
    'drum',
    'whistle',
    'puzzle',
    'block',
    'yo-yo',
    'jump rope',
    'swing',
    'slide',
    'sandbox',
    'seesaw',
    'bucket',
    'shovel',
    'sandcastle',
    'beach',
    'sea',
    'river',
    'lake',
    'pond',
    'island',
    'mountain',
    'hill',
    'forest',
    'field',
    'garden',
    'farm',
    'barn',
    'tractor',
    'fence',
    'gate',
    'door',
    'window',
    'roof',
    'chimney',
    'wall',
    'floor',
    'stairs',
    'chair',
    'sofa',
    'pillow',
    'blanket',
    'lamp',
    'mirror',
    'bathtub',
    'shower',
    'soap',
    'towel',
    'toothbrush',
    'toothpaste',
    'comb',
    'sponge',
    'cup',
    'plate',
    'bowl',
    'fork',
    'pot',
    'pan',
    'kettle',
    'oven',
    'fridge',
    'sink',
    'bread',
    'butter',
    'cheese',
    'egg',
    'sandwich',
    'soup',
    'pizza',
    'pasta',
    'rice',
    'cookie',
    'candy',
    'chocolate',
    'lollipop',
    'pancake',
    'honey',
    'jam',
    'juice',
    'water',
    'tea',
    'orange',
    'pear',
    'grape',
    'strawberry',
    'cherry',
    'watermelon',
    'lemon',
    'peach',
    'plum',
    'pineapple',
    'carrot',
    'potato',
    'tomato',
    'cucumber',
    'onion',
    'pumpkin',
    'corn',
    'mushroom',
    'nut',
    'popcorn',
    'shirt',
    'dress',
    'skirt',
    'pants',
    'shorts',
    'sock',
    'shoe',
    'boot',
    'sandal',
    'coat',
    'jacket',
    'sweater',
    'scarf',
    'glove',
    'mitten',
    'cap',
    'pajamas',
    'button',
    'zipper',
    'pocket',
    'backpack',
    'bag',
    'wallet',
    'key',
    'lock',
    'phone',
    'television',
    'computer',
    'camera',
    'radio',
    'bell',
    'candle',
    'flashlight',
    'pencil',
    'pen',
    'crayon',
    'marker',
    'paper',
    'notebook',
    'eraser',
    'ruler',
    'scissors',
    'glue',
    'paint',
    'brush',
    'chalk',
    'blackboard',
    'teacher',
    'school',
    'classroom',
    'bus',
    'truck',
    'boat',
    'ship',
    'rocket',
    'helicopter',
    'fire truck',
    'ambulance',
    'police car',
    'taxi',
    'motorcycle',
    'scooter',
    'skateboard',
    'sled',
    'wheel',
    'road',
    'bridge',
    'tunnel',
    'street',
    'park',
    'playground',
    'zoo',
    'hospital',
    'doctor',
    'nurse',
    'firefighter',
    'police officer',
    'farmer',
    'baker',
    'cook',
    'pilot',
    'astronaut',
    'mail',
    'letter',
    'gift',
    'birthday',
    'party',
    'song',
    'dance',
    'music',
    'picture',
    'photo',
    'map',
    'treasure',
    'crown',
    'wand',
    'castle',
    'tower',
    'tent',
    'campfire',
    'fishing rod',
    'nest',
    'feather',
    'leaf',
    'branch',
    'root',
    'grass',
    'stone',
    'sand',
    'shell',
    'wave',
    'wind',
    'storm',
    'thunder',
    'lightning',
    'ice',
    'puddle',
    'mud',
    'fire',
    'smoke',
    'night',
    'morning',
    'sleep',
    'dream',
    'hug',
    'kiss',
    'smile',
    'laugh',
    'tear',
    'sneeze',
    'hiccup',
    'yawn',
    'whisper',
    'shout',
    'jumping',
    'running',
    'swimming',
    'climbing',
    'hide-and-seek',
    'tag',
    'circus',
    'magic',
    'magician',
    'monster',
    'train station',
    'bus stop',
    'grandma',
    'grandpa',
    'baby',
    'family',
    'friend',
    'neighbor',
    'glasses',
    'sunglasses',
    'necklace',
    'ring',
    'bracelet',
    'watch',
    'earring',
    'ribbon',
    'bow',
    'sticker',
    'bubble',
    'paper boat',
    'paper plane',
    'snowball',
    'snowflake',
    'icicle',
    'hot dog',
    'hamburger',
    'spaghetti',
    'yogurt',
    'cereal',
    'porridge',
    'muffin',
    'donut',
    'pie',
    'ketchup',
    'salt',
    'sugar',
    'flour',
    'broom',
    'basket',
    'box',
    'bottle',
    'jar',
    'brick',
    'hammer',
    'nail',
    'saw',
    'ladder',
    'rope',
    'tape',
    'fan',
    'heater',
    'curtain',
    'carpet',
    'cupboard',
    'drawer',
    'shelf',
    'closet',
    'hanger',
    'piggy bank',
    'coin',
    'money',
    'store',
    'market',
    'cash register',
    'ticket',
    'cartoon',
    'movie',
    'game',
    'card',
    'dice',
    'chess',
    'cube',
    'marble',
    'rattle',
    'pacifier',
    'stroller',
    'crib',
    'diaper',
    'potty',
    'highchair',
    'bib',
    'cowboy',
    'eggshell',
    'windowsill',
    'spinning top',
    'pea',
    'roller skate',
    'trash can',
  ],
  normal: [
    'alarm clock',
    'vacuum cleaner',
    'traffic light',
    'library',
    'refrigerator',
    'compass',
    'telescope',
    'guitar',
    'piano',
    'parachute',
    'mail carrier',
    'volcano',
    'desert',
    'lighthouse',
    'suitcase',
    'calendar',
    'microscope',
    'binoculars',
    'firework',
    'maze',
    'merry-go-round',
    'waterfall',
    'paper clip',
    'scarecrow',
    'railroad',
    'microwave',
    'washing machine',
    'dishwasher',
    'coffee maker',
    'toaster',
    'blender',
    'hair dryer',
    'air conditioner',
    'laptop',
    'tablet',
    'keyboard',
    'printer',
    'remote control',
    'antenna',
    'video camera',
    'calculator',
    'doorbell',
    'keyhole',
    'attic',
    'basement',
    'pantry',
    'hallway',
    'living room',
    'bedroom',
    'porch',
    'fireplace',
    'chandelier',
    'lampshade',
    'nightstand',
    'dresser',
    'stool',
    'hammock',
    'mattress',
    'pillowcase',
    'clothespin',
    'ironing board',
    'stepladder',
    'extension cord',
    'tape measure',
    'pliers',
    'drill',
    'screwdriver',
    'screw',
    'wrench',
    'envelope',
    'stamp',
    'postcard',
    'package',
    'receipt',
    'safe',
    'credit card',
    'bill',
    'checkout',
    'shopping cart',
    'fitting room',
    'escalator',
    'elevator',
    'turnstile',
    'passport',
    'luggage',
    'customs',
    'airport',
    'platform',
    'subway',
    'conductor',
    'flight attendant',
    'captain',
    'anchor',
    'sail',
    'oar',
    'life jacket',
    'harbor',
    'pier',
    'ferry',
    'yacht',
    'canoe',
    'raft',
    'scuba diving',
    'wetsuit',
    'diver',
    'surfing',
    'snowboard',
    'figure skating',
    'hockey',
    'soccer',
    'basketball',
    'volleyball',
    'tennis',
    'ping-pong',
    'badminton',
    'checkers',
    'domino',
    'bingo',
    'crossword',
    'riddle',
    'quiz',
    'relay race',
    'marathon',
    'stadium',
    'referee',
    'coach',
    'goalkeeper',
    'goal',
    'puck',
    'racket',
    'net',
    'dumbbell',
    'trampoline',
    'water park',
    'amusement park',
    'roller coaster',
    'theater',
    'museum',
    'exhibition',
    'gallery',
    'concert',
    'orchestra',
    'violin',
    'trumpet',
    'harmonica',
    'accordion',
    'flute',
    'microphone',
    'headphones',
    'speaker',
    'stage',
    'audience',
    'applause',
    'ticket office',
    'popcorn machine',
    'director',
    'actor',
    'costume',
    'mask',
    'makeup',
    'wig',
    'hairdresser',
    'barber',
    'dentist',
    'vet',
    'pharmacy',
    'pharmacist',
    'bandage',
    'thermometer',
    'pill',
    'vaccine',
    'x-ray',
    'lifeguard',
    'plumber',
    'electrician',
    'mechanic',
    'architect',
    'engineer',
    'scientist',
    'journalist',
    'photographer',
    'librarian',
    'lawyer',
    'judge',
    'mayor',
    'president',
    'tourist',
    'guide',
    'backpacker',
    'sleeping bag',
    'lantern',
    'thermos',
    'picnic',
    'barbecue',
    'grill',
    'campsite',
    'hiking',
    'fishing',
    'bird watching',
    'greenhouse',
    'vegetable garden',
    'flower bed',
    'lawn mower',
    'watering can',
    'wheelbarrow',
    'rake',
    'hose',
    'sprinkler',
    'hedge',
    'beehive',
    'windmill',
    'well',
    'bakery',
    'butcher',
    'grocery store',
    'supermarket',
    'farmers market',
    'department store',
    'bookstore',
    'post office',
    'bank',
    'police station',
    'fire station',
    'town hall',
    'courthouse',
    'school bus',
    'kindergarten',
    'university',
    'dormitory',
    'homework',
    'exam',
    'report card',
    'diploma',
    'graduation',
    'recess',
    'lunch box',
    'cafeteria',
    'principal',
    'textbook',
    'dictionary',
    'encyclopedia',
    'atlas',
    'globe',
    'magnifying glass',
    'hourglass',
    'sundial',
    'barometer',
    'weather vane',
    'compass rose',
    'satellite',
    'space station',
    'planet',
    'comet',
    'meteor',
    'galaxy',
    'eclipse',
    'constellation',
    'iceberg',
    'glacier',
    'avalanche',
    'earthquake',
    'tornado',
    'hurricane',
    'flood',
    'drought',
    'fog',
    'frost',
    'hail',
    'sunrise',
    'sunset',
    'tide',
    'cave',
    'canyon',
    'cliff',
    'valley',
    'swamp',
    'jungle',
    'savanna',
    'oasis',
    'geyser',
    'coral reef',
    'peninsula',
    'bay',
    'chameleon',
    'flamingo',
    'peacock',
    'ostrich',
    'eagle',
    'woodpecker',
    'seagull',
    'swan',
    'bat',
    'raccoon',
    'skunk',
    'beaver',
    'otter',
    'walrus',
    'polar bear',
    'moose',
    'llama',
    'porcupine',
    'armadillo',
    'sloth',
    'lizard',
    'seahorse',
    'stingray',
    'lobster',
    'mosquito',
    'dragonfly',
    'grasshopper',
    'firefly',
    'cocoon',
    'tadpole',
    'pinecone',
    'acorn',
    'cactus',
    'sunflower',
    'dandelion',
    'bamboo',
    'moss',
    'recipe',
    'cookbook',
    'apron',
    'oven mitt',
    'rolling pin',
    'whisk',
    'ladle',
    'cutting board',
    'frying pan',
    'colander',
    'grater',
    'can opener',
    'teapot',
    'sugar bowl',
    'napkin',
    'tablecloth',
    'tray',
    'dessert',
    'appetizer',
    'buffet',
    'restaurant',
    'waiter',
    'menu',
    'tip',
    'chef',
    'takeout',
    'drive-through',
    'vending machine',
    'gas station',
    'parking lot',
    'traffic jam',
    'speed bump',
    'crosswalk',
    'sidewalk',
    'roundabout',
    'highway',
    'seat belt',
    'steering wheel',
    'windshield',
    'flat tire',
    'driver\'s license',
    'car wash',
    'garage',
    'trailer',
    'motorhome',
    'cable car',
    'ski lift',
    'sled dog',
    'snowplow',
    'snowmobile',
    'igloo',
    'umbrella stand',
    'coat rack',
    'doormat',
    'mailbox',
    'key chain',
    'battery',
    'charger',
    'light bulb',
    'power outage',
    'password',
    'email',
    'website',
    'video call',
    'selfie',
    'emoji',
    'podcast',
    'cartoon character',
    'comic book',
    'fairy tale',
    'nursery rhyme',
    'bedtime story',
    'lullaby',
    'babysitter',
    'sleepover',
    'pillow fight',
    'board game',
    'jigsaw puzzle',
    'card trick',
    'magic trick',
    'treasure hunt',
    'scavenger hunt',
    'costume party',
    'talent show',
    'science fair',
    'field trip',
    'summer camp',
    'vacation',
    'souvenir',
    'hotel',
    'reception',
    'room service',
    'swimming pool',
    'diving board',
    'sunscreen',
    'flip-flop',
    'beach towel',
    'lifebuoy',
    'spacesuit',
    'ski',
  ],
  hard: [
    'inspiration',
    'patience',
    'echo',
    'nostalgia',
    'doubt',
    'tradition',
    'habit',
    'curiosity',
    'horizon',
    'gravity',
    'illusion',
    'compromise',
    'reputation',
    'intuition',
    'politeness',
    'gratitude',
    'landmark',
    'balance',
    'weightlessness',
    'coincidence',
    'reflection',
    'memory',
    'adventure',
    'invention',
    'journey',
    'competition',
    'mood',
    'silence',
    'secret',
    'procrastination',
    'eternity',
    'infinity',
    'destiny',
    'luck',
    'chance',
    'pattern',
    'paradox',
    'contradiction',
    'harmony',
    'chaos',
    'order',
    'symmetry',
    'proportion',
    'perspective',
    'contrast',
    'shade',
    'silhouette',
    'shadow',
    'mirage',
    'resonance',
    'vibration',
    'inertia',
    'friction',
    'attraction',
    'pressure',
    'temperature',
    'humidity',
    'atmosphere',
    'climate',
    'ecology',
    'evolution',
    'civilization',
    'culture',
    'art',
    'philosophy',
    'psychology',
    'democracy',
    'constitution',
    'law',
    'justice',
    'freedom',
    'equality',
    'responsibility',
    'duty',
    'privilege',
    'etiquette',
    'ceremony',
    'ritual',
    'custom',
    'superstition',
    'omen',
    'legend',
    'myth',
    'fable',
    'proverb',
    'quote',
    'metaphor',
    'irony',
    'sarcasm',
    'sense of humor',
    'pun',
    'hint',
    'plot',
    'cliffhanger',
    'climax',
    'happy ending',
    'prologue',
    'introduction',
    'conclusion',
    'argument',
    'proof',
    'hypothesis',
    'theory',
    'experiment',
    'discovery',
    'progress',
    'revolution',
    'reform',
    'crisis',
    'inflation',
    'budget',
    'tax',
    'loan',
    'investment',
    'profit',
    'loss',
    'advertising',
    'slogan',
    'logo',
    'interview',
    'rumor',
    'gossip',
    'headline',
    'breaking news',
    'election',
    'vote',
    'parliament',
    'embassy',
    'diplomacy',
    'negotiation',
    'alliance',
    'treaty',
    'agreement',
    'contract',
    'signature',
    'document',
    'archive',
    'chronicle',
    'biography',
    'autobiography',
    'memoir',
    'dynasty',
    'inheritance',
    'heritage',
    'heirloom',
    'antique',
    'collection',
    'restoration',
    'masterpiece',
    'forgery',
    'original',
    'copy',
    'plagiarism',
    'pseudonym',
    'incognito',
    'disguise',
    'code',
    'mystery',
    'intention',
    'motivation',
    'ambition',
    'fantasy',
    'imagination',
    'creativity',
    'improvisation',
    'talent',
    'genius',
    'skill',
    'experience',
    'wisdom',
    'knowledge',
    'ignorance',
    'naivety',
    'honesty',
    'loyalty',
    'betrayal',
    'trust',
    'jealousy',
    'envy',
    'pride',
    'modesty',
    'shyness',
    'confidence',
    'courage',
    'fear',
    'anxiety',
    'relief',
    'surprise',
    'disappointment',
    'embarrassment',
    'boredom',
    'enthusiasm',
    'excitement',
    'happiness',
    'sadness',
    'loneliness',
    'friendship',
    'kindness',
    'generosity',
    'greed',
    'selfishness',
    'empathy',
    'sympathy',
    'compassion',
    'forgiveness',
    'apology',
    'regret',
    'guilt',
    'conscience',
    'temptation',
    'willpower',
    'discipline',
    'routine',
    'schedule',
    'deadline',
    'priority',
    'multitasking',
    'efficiency',
    'productivity',
    'laziness',
    'perfectionism',
    'optimism',
    'pessimism',
    'sense of direction',
    'common sense',
    'first impression',
    'small talk',
    'body language',
    'sign language',
    'accent',
    'dialect',
    'translation',
    'vocabulary',
    'grammar',
    'spelling',
    'punctuation',
    'alphabet',
    'handwriting',
    'signature move',
    'nickname',
    'fame',
    'celebrity',
    'influence',
    'authority',
    'power',
    'leadership',
    'teamwork',
    'cooperation',
    'rivalry',
    'victory',
    'defeat',
    'tie',
    'comeback',
    'underdog',
    'jackpot',
    'bargain',
    'discount',
    'refund',
    'warranty',
    'subscription',
    'membership',
    'loyalty card',
    'rent',
    'mortgage',
    'salary',
    'bonus',
    'pension',
    'retirement',
    'promotion',
    'resignation',
    'unemployment',
    'career',
    'profession',
    'hobby',
    'passion',
    'obsession',
    'nightmare',
    'daydream',
    'sleepwalking',
    'insomnia',
    'jet lag',
    'homesickness',
    'wanderlust',
    'culture shock',
    'generation gap',
    'midlife crisis',
    'peer pressure',
    'role model',
    'comfort zone',
    'bucket list',
    'wishful thinking',
    'second thought',
    'gut feeling',
    'hindsight',
    'foresight',
    'deja vu',
    'premonition',
    'telepathy',
    'hypnosis',
    'meditation',
    'mindfulness',
    'self-esteem',
    'identity',
    'personality',
    'character',
    'temperament',
    'instinct',
    'reflex',
    'habitat',
    'ecosystem',
    'biodiversity',
    'extinction',
    'migration',
    'hibernation',
    'camouflage',
    'metamorphosis',
    'photosynthesis',
    'pollution',
    'recycling',
    'global warming',
    'renewable energy',
    'electricity',
    'magnetism',
    'radiation',
    'energy',
    'speed',
    'distance',
    'direction',
    'dimension',
    'volume',
    'weight',
    'density',
    'probability',
    'statistics',
    'average',
    'percentage',
    'fraction',
    'equation',
    'estimate',
    'guess',
    'clue',
    'evidence',
    'alibi',
    'witness',
    'suspect',
    'verdict',
    'jury',
    'lawsuit',
    'tolerance',
    'diversity',
    'charity',
    'volunteer',
    'donation',
    'fundraiser',
    'petition',
    'protest',
    'strike',
    'boycott',
    'propaganda',
    'censorship',
    'privacy',
    'surveillance',
    'algorithm',
    'artificial intelligence',
    'virtual reality',
    'innovation',
    'prototype',
    'blueprint',
    'trademark',
    'monopoly',
    'startup',
    'bankruptcy',
    'supply and demand',
    'economy',
    'globalization',
    'tourism',
    'hospitality',
    'bureaucracy',
    'red tape',
    'loophole',
    'exception',
    'rule of thumb',
    'trial and error',
    'cause and effect',
    'chain reaction',
    'domino effect',
    'butterfly effect',
    'snowball effect',
    'tipping point',
    'point of view',
    'turning point',
    'milestone',
    'anniversary',
    'reunion',
    'farewell',
    'welcome',
    'invitation',
    'surprise party',
    'compliment',
    'criticism',
    'feedback',
    'advice',
    'promise',
    'bet',
    'dare',
    'challenge',
    'dilemma',
    'patent',
  ],
} satisfies Record<AliasLevel, string[]>
