import type { AliasLevel } from '~/types'

/**
 * Слова Alias на английском: собираются отдельно, а не переводом русских; строчные, ≤ 24 символов.
 * Временный набор по 30 слов на уровень — полный список (350–450 на уровень) придёт отдельно.
 */
export default {
  easy: [
    'cat',
    'dog',
    'ball',
    'apple',
    'house',
    'sun',
    'car',
    'fish',
    'book',
    'table',
    'spoon',
    'bird',
    'flower',
    'tree',
    'milk',
    'cake',
    'hat',
    'umbrella',
    'train',
    'airplane',
    'horse',
    'giraffe',
    'banana',
    'clock',
    'bed',
    'star',
    'snowman',
    'bicycle',
    'ice cream',
    'butterfly',
  ],
  normal: [
    'alarm clock',
    'vacuum cleaner',
    'traffic light',
    'library',
    'refrigerator',
    'rainbow',
    'compass',
    'telescope',
    'flashlight',
    'tent',
    'guitar',
    'piano',
    'parachute',
    'mail carrier',
    'volcano',
    'desert',
    'lighthouse',
    'suitcase',
    'calendar',
    'microscope',
    'binoculars',
    'kangaroo',
    'octopus',
    'rocket',
    'fireworks',
    'maze',
    'merry-go-round',
    'waterfall',
    'paper clip',
    'scarecrow',
  ],
  hard: [
    'inspiration',
    'patience',
    'echo',
    'nostalgia',
    'doubt',
    'tradition',
    'habit',
    'curiosity',
    'horizon',
    'gravity',
    'illusion',
    'compromise',
    'reputation',
    'intuition',
    'politeness',
    'gratitude',
    'landmark',
    'balance',
    'weightlessness',
    'coincidence',
    'reflection',
    'memory',
    'adventure',
    'invention',
    'journey',
    'competition',
    'mood',
    'silence',
    'secret',
    'procrastination',
  ],
} satisfies Record<AliasLevel, string[]>
