import type { Deck } from '~/types'

export default {
  id: 'en-childhood',
  lang: 'en',
  type: 'most-likely',
  title: 'Childhood & School',
  emoji: '🎒',
  questions: [
    'Who’s most likely to have been the teacher’s pet?',
    'Who’s most likely to have written “I will not talk in class” fifty times?',
    'Who’s most likely to have sold candy from their locker for profit?',
    'Who’s most likely to have run a lemonade stand that actually turned a profit?',
    'Who’s most likely to have faked a fever with a warm thermometer?',
    'Who’s most likely to have eaten glue and insisted it was on purpose?',
    'Who’s most likely to have reminded the teacher about the homework?',
    'Who’s most likely to have had an imaginary friend with a full backstory?',
    'Who’s most likely to have gotten stuck in the playground slide?',
    'Who’s most likely to have staged a play in the living room and charged admission?',
    'Who’s most likely to have brought a snail to show-and-tell?',
    'Who’s most likely to have run away from home and stopped at the corner?',
    'Who’s most likely to have been picked last in gym and secretly relieved?',
    'Who’s most likely to have traded their lunch for something way worse?',
    'Who’s most likely to have had a crush on a cartoon character?',
    'Who’s most likely to have built a blanket fort that took over the whole house?',
    'Who’s most likely to have hidden a report card under the mattress?',
    'Who’s most likely to have ridden a bike straight into a parked car?',
    'Who’s most likely to have collected rocks and called it a museum?',
    'Who’s most likely to have been sent to the principal for being too funny?',
    'Who’s most likely to have known every dinosaur name and used them in arguments?',
    'Who’s most likely to have written a love note and slipped it into the wrong desk?',
    'Who’s most likely to have finished a whole book series in one weekend?',
    'Who’s most likely to have had a secret handshake with their best friend?',
    'Who’s most likely to have been a hall monitor who took the job very seriously?',
    'Who’s most likely to have peeked at the presents and acted surprised anyway?',
    'Who’s most likely to have brought a note “from Mom” in their own handwriting?',
    'Who’s most likely to have chosen the tuba because it was the biggest?',
    'Who’s most likely to have had a zoo of stuffed animals, each with a name?',
    'Who’s most likely to have been the goalie because nobody else would?',
    'Who’s most likely to have started a club with exactly one member?',
    'Who’s most likely to have read under the covers with a flashlight?',
    'Who’s most likely to have gotten lost in a supermarket and enjoyed it?',
    'Who’s most likely to have won the science fair with a baking-soda volcano?',
    'Who’s most likely to have practiced their autograph for future fame?',
    'Who’s most likely to have licked a frozen pole just to see what happens?',
    'Who’s most likely to have been the class clown and the class brain at once?',
    'Who’s most likely to have thrown a toy-store tantrum people still talk about?',
    'Who’s most likely to have refused to go anywhere without a superhero cape?',
    'Who’s most likely to have taught the family dog exactly one trick?',
    'Who’s most likely to have read the encyclopedia for fun?',
    'Who’s most likely to have gotten a gold star and framed it?',
    'Who’s most likely to have demanded a raise from the tooth fairy?',
    'Who’s most likely to have cried at the first day of school — as a parent?',
  ],
} satisfies Deck
