import type { Deck } from '~/types'

export default {
  id: 'en-deep-talk',
  lang: 'en',
  type: 'would-you-rather',
  title: 'Deep Talk',
  emoji: '🌌',
  questions: [
    'Would you rather be respected or liked?',
    'Would you rather know how you’ll die or when?',
    'Would you rather have a life full of adventure or a life full of peace?',
    'Would you rather lose all your memories or never make new ones?',
    'Would you rather be remembered for a hundred years or forgotten but truly happy?',
    'Would you rather be honest and hurt someone or lie and protect them?',
    'Would you rather have one lifelong friend or many friends who come and go?',
    'Would you rather live without music or without books?',
    'Would you rather know the truth about everything or be content not knowing?',
    'Would you rather have less time but more freedom, or more time but more duties?',
    'Would you rather change one thing in your past or one thing about yourself now?',
    'Would you rather do work you love that pays little or work you tolerate that pays well?',
    'Would you rather be the smartest person in the room or the kindest?',
    'Would you rather be alone with your thoughts for a year or never alone at all?',
    'Would you rather forgive and forget or remember and move on?',
    'Would you rather your life were a comedy or a drama?',
    'Would you rather have certainty about the future or the freedom to change it?',
    'Would you rather live in a world without lies or a world without secrets?',
    'Would you rather be loved deeply by one person or admired by thousands?',
    'Would you rather leave the world a little better or be happy every day of your life?',
    'Would you rather know what everyone honestly thinks of you or never wonder again?',
    'Would you rather have a short life full of meaning or a long one that’s comfortable?',
    'Would you rather your children turn out just like you or nothing like you?',
    'Would you rather lose your sight or your hearing?',
    'Would you rather regret what you did or what you didn’t do?',
    'Would you rather be the one who leaves or the one who gets left?',
    'Would you rather chase a dream and fail or never try and always wonder?',
    'Would you rather grow old with someone or stay young alone?',
    'Would you rather have the answers or the right questions?',
    'Would you rather live your life again exactly as it was or a different one entirely?',
    'Would you rather be understood by a few or misunderstood by many who love you?',
    'Would you rather have peace of mind or a purpose that keeps you up at night?',
    'Would you rather fix the world’s biggest problem or your own hardest one?',
    'Would you rather know your purpose or be free to invent one?',
    'Would you rather be right or be at peace?',
    'Would you rather feel every moment and forget it, or remember everything but feel nothing?',
    'Would you rather be brave once when it matters or careful your whole life?',
    'Would you rather your best years be behind you or still ahead?',
    'Would you rather be the mentor or the student, for life?',
    'Would you rather trust everyone and sometimes be hurt or trust no one and be safe?',
    'Would you rather be part of something great or be great on your own?',
    'Would you rather say everything you feel or keep the peace?',
    'Would you rather know that everything happens for a reason or that nothing does?',
    'Would you rather be needed or be free?',
  ],
} satisfies Deck
