import type { Deck } from '~/types'

export default {
  id: 'en-food',
  lang: 'en',
  type: 'most-likely',
  title: 'Food',
  emoji: '🍕',
  questions: [
    'Who’s most likely to order the same thing at every restaurant?',
    'Who’s most likely to try mayo on ice cream just to see?',
    'Who’s most likely to eat a whole pizza and ask what’s for dessert?',
    'Who’s most likely to photograph their food before anyone can touch it?',
    'Who’s most likely to burn water?',
    'Who’s most likely to follow a recipe exactly and still end up with soup?',
    'Who’s most likely to say “I’m not hungry” and eat off everyone’s plate?',
    'Who’s most likely to have a secret snack drawer at work?',
    'Who’s most likely to eat the pizza crusts everyone else leaves behind?',
    'Who’s most likely to put ketchup on absolutely everything?',
    'Who’s most likely to argue that a hot dog is a sandwich?',
    'Who’s most likely to eat dessert first because life is short?',
    'Who’s most likely to keep a sauce bottle two years past its date?',
    'Who’s most likely to bake bread at 3 a.m. because they couldn’t sleep?',
    'Who’s most likely to eat a lemon like an orange?',
    'Who’s most likely to order for the whole table without asking?',
    'Who’s most likely to have strong opinions on the correct way to cut a sandwich?',
    'Who’s most likely to spend an hour choosing a restaurant and then get takeout?',
    'Who’s most likely to decide they’re a chef after one cooking show?',
    'Who’s most likely to eat spicy food until they cry and then order more?',
    'Who’s most likely to dip fries in a milkshake and defend it?',
    'Who’s most likely to have a favorite mug for soup?',
    'Who’s most likely to grow a whole herb garden and never cook with it?',
    'Who’s most likely to eat pasta for breakfast, lunch, and dinner?',
    'Who’s most likely to take charge of the grill and burn everything?',
    'Who’s most likely to order a salad and eat everyone else’s fries?',
    'Who’s most likely to know the closing time of every kebab shop in town?',
    'Who’s most likely to eat the garnish?',
    'Who’s most likely to put pineapple on pizza and refuse to apologize?',
    'Who’s most likely to treat a tasting menu like a challenge?',
    'Who’s most likely to cook one dish so well they never learn another?',
    'Who’s most likely to hide the good chocolate from their own family?',
    'Who’s most likely to eat chips with chopsticks to keep their fingers clean?',
    'Who’s most likely to drink pickle juice straight from the jar?',
    'Who’s most likely to carry a bottle of hot sauce in their bag?',
    'Who’s most likely to start a diet and quit before lunch?',
    'Who’s most likely to eat soup with a fork?',
    'Who’s most likely to have strong feelings about how to hold a taco?',
    'Who’s most likely to go vegetarian after one documentary?',
    'Who’s most likely to eat cold leftovers at the counter at midnight?',
    'Who’s most likely to save the best bite for last and lose it to someone else?',
    'Who’s most likely to put cheese on a dessert?',
    'Who’s most likely to judge a restaurant by its bread basket?',
    'Who’s most likely to eat birthday cake for breakfast the next day?',
  ],
} satisfies Deck
