import type { Deck } from '~/types'

export default {
  id: 'en-home-habits',
  lang: 'en',
  type: 'most-likely',
  title: 'Home & Habits',
  emoji: '🏠',
  questions: [
    'Who’s most likely to set six alarms with names like “seriously, get up”?',
    'Who’s most likely to have a chair that’s really a second wardrobe?',
    'Who’s most likely to leave the dishwasher clean and unloaded for three days?',
    'Who’s most likely to water a plastic plant?',
    'Who’s most likely to have forty browser tabs open at all times?',
    'Who’s most likely to keep the “good” towels for guests who never come?',
    'Who’s most likely to let a cup of tea go cold and just make a new one?',
    'Who’s most likely to shout at the TV like the players can hear them?',
    'Who’s most likely to sort the recycling more carefully than their taxes?',
    'Who’s most likely to have a junk drawer that’s grown into a junk room?',
    'Who’s most likely to be in bed by nine and up at five on purpose?',
    'Who’s most likely to make the bed only on the day the sheets get changed?',
    'Who’s most likely to talk to the robot vacuum like it’s a pet?',
    'Who’s most likely to leave laundry in the washer until it needs washing again?',
    'Who’s most likely to alphabetize the spice rack?',
    'Who’s most likely to use a stack of unread books as a nightstand?',
    'Who’s most likely to keep the plastic film on a new remote for a year?',
    'Who’s most likely to eat toast over the sink to avoid making crumbs?',
    'Who’s most likely to lose the remote inside the couch every single week?',
    'Who’s most likely to start a deep clean and stop halfway to read old letters?',
    'Who’s most likely to buy a treadmill and use it as a coat rack?',
    'Who’s most likely to hoard takeout sauce packets in a kitchen drawer?',
    'Who’s most likely to open the fridge three times hoping something new appeared?',
    'Who’s most likely to say “I’ll fix it this weekend” for an entire year?',
    'Who’s most likely to sing in the shower loud enough for the neighbors to learn the lyrics?',
    'Who’s most likely to leave one sip in the milk carton and put it back?',
    'Who’s most likely to have a smart home that only they know how to operate?',
    'Who’s most likely to keep a plant alive for years without knowing what it is?',
    'Who’s most likely to fold a fitted sheet perfectly and brag about it?',
    'Who’s most likely to have a “floordrobe” instead of a wardrobe?',
    'Who’s most likely to own a label maker and label the label maker?',
    'Who’s most likely to hide a spare key under a doormat that fools no one?',
    'Who’s most likely to leave the lights on in every room they’ve ever walked through?',
    'Who’s most likely to have a candle they’re “saving” and will never light?',
    'Who’s most likely to rearrange all the furniture at midnight on a whim?',
    'Who’s most likely to label their food in the fridge and still lose it?',
    'Who’s most likely to own ten mugs and use the same one every day?',
    'Who’s most likely to click “remind me tomorrow” on updates for six months?',
    'Who’s most likely to keep a drawer of dead batteries “to test later”?',
    'Who’s most likely to put off changing a lightbulb until the room goes dark?',
    'Who’s most likely to clean the house before the cleaner arrives?',
    'Who’s most likely to eat the last slice and put the empty box back?',
    'Who’s most likely to have a shoe pile blocking the front door?',
    'Who’s most likely to leave the bathroom fan running all night?',
    'Who’s most likely to put chores on a calendar and snooze every single one?',
  ],
} satisfies Deck
