import type { Deck } from '~/types'

export default {
  id: 'en-never-have-i',
  lang: 'en',
  type: 'never-have-i',
  title: 'Never Have I Ever',
  emoji: '🙈',
  questions: [
    'Never have I ever been on TV.',
    'Never have I ever broken a bone.',
    'Never have I ever ridden a horse.',
    'Never have I ever stayed up a whole night without sleeping at all.',
    'Never have I ever sent a message to the wrong person.',
    'Never have I ever been to a concert alone.',
    'Never have I ever had a surprise party thrown for me.',
    'Never have I ever locked myself out of my own home.',
    'Never have I ever eaten something off the floor.',
    'Never have I ever cut my own hair.',
    'Never have I ever fallen asleep in a cinema.',
    'Never have I ever met someone famous.',
    'Never have I ever mumbled through a whole song pretending to know the words.',
    'Never have I ever driven more than ten hours in one day.',
    'Never have I ever been fired.',
    'Never have I ever had a pet with a ridiculous name.',
    'Never have I ever swum in the ocean at night.',
    'Never have I ever returned a gift for cash.',
    'Never have I ever finished a puzzle with more than a thousand pieces.',
    'Never have I ever gone a week without a shower.',
    'Never have I ever laughed so hard I couldn’t breathe.',
    'Never have I ever hidden a purchase from my family.',
    'Never have I ever slept in an airport.',
    'Never have I ever won anything in a raffle.',
    'Never have I ever cooked a meal that nobody would eat.',
    'Never have I ever gotten a tattoo.',
    'Never have I ever cried at a TV commercial.',
    'Never have I ever been in a helicopter.',
    'Never have I ever spent a whole day in pajamas.',
    'Never have I ever run a race longer than 5K.',
    'Never have I ever talked to myself out loud in public.',
    'Never have I ever forgotten someone’s name while introducing them.',
    'Never have I ever waited in line for more than three hours.',
    'Never have I ever eaten an entire cake by myself.',
    'Never have I ever been to a wedding where I didn’t know the couple.',
    'Never have I ever milked a cow.',
    'Never have I ever seen a shooting star.',
    'Never have I ever lied about my age.',
    'Never have I ever ridden a rollercoaster three times in a row.',
    'Never have I ever slept through an alarm and missed something important.',
    'Never have I ever been in a food fight.',
    'Never have I ever kept a diary.',
    'Never have I ever climbed a tree as an adult.',
    'Never have I ever taken a selfie with a stranger.',
    'Never have I ever been on a blind date.',
    'Never have I ever walked into the wrong bathroom by accident.',
    'Never have I ever been stuck in traffic for more than four hours.',
    'Never have I ever performed on a stage.',
    'Never have I ever built a snowman taller than me.',
    'Never have I ever planted a tree.',
  ],
} satisfies Deck
