import type { Deck } from '~/types'

export default {
  id: 'en-nhie-childhood',
  lang: 'en',
  type: 'never-have-i',
  title: 'Childhood & School',
  emoji: '🧸',
  questions: [
    'Never have I ever cheated on a test.',
    'Never have I ever skipped class.',
    'Never have I ever eaten snow.',
    'Never have I ever hidden a bad report card.',
    'Never have I ever kept a diary.',
    'Never have I ever had a pet with a ridiculous name.',
    'Never have I ever been in a food fight.',
    'Never have I ever broken a bone as a kid.',
    'Never have I ever forged a parent’s signature.',
    'Never have I ever believed in Santa past the age of eight.',
    'Never have I ever read under the covers with a flashlight.',
    'Never have I ever worn hand-me-downs.',
    'Never have I ever been sent to the principal’s office.',
    'Never have I ever faked being sick to stay home from school.',
    'Never have I ever had a crush on a teacher.',
    'Never have I ever passed notes in class.',
    'Never have I ever built a fort out of couch cushions.',
    'Never have I ever been afraid of the dark.',
    'Never have I ever fallen asleep in class.',
    'Never have I ever broken a window with a ball.',
    'Never have I ever run away from home for an afternoon.',
    'Never have I ever been in the school choir or band.',
    'Never have I ever eaten glue or paste.',
    'Never have I ever collected stickers or trading cards.',
    'Never have I ever brought a stray animal home.',
    'Never have I ever worn braces.',
    'Never have I ever been to summer camp.',
    'Never have I ever had an imaginary friend.',
    'Never have I ever been picked last in gym class.',
    'Never have I ever gotten detention.',
    'Never have I ever played a video game after bedtime.',
    'Never have I ever had a lemonade stand.',
    'Never have I ever lost a tooth while eating an apple.',
    'Never have I ever cried on the first day of school.',
    'Never have I ever been the teacher’s pet.',
    'Never have I ever traded my lunch for something better.',
    'Never have I ever won a spelling bee or a science fair.',
    'Never have I ever blamed the dog for something I did.',
    'Never have I ever gone to prom.',
    'Never have I ever been class president.',
    'Never have I ever slept with a night light.',
    'Never have I ever gotten stuck on the monkey bars.',
    'Never have I ever had a secret handshake with a friend.',
    'Never have I ever gotten a gold star on a chart.',
    'Never have I ever glued my fingers together.',
  ],
} satisfies Deck
