import type { Deck } from '~/types'

export default {
  id: 'en-nhie-food',
  lang: 'en',
  type: 'never-have-i',
  title: 'Food',
  emoji: '🍜',
  questions: [
    'Never have I ever eaten something off the floor.',
    'Never have I ever cooked a meal that nobody would eat.',
    'Never have I ever eaten an entire cake by myself.',
    'Never have I ever eaten insects on purpose.',
    'Never have I ever had cereal for dinner.',
    'Never have I ever drunk pickle juice from the jar.',
    'Never have I ever eaten cold pizza for breakfast.',
    'Never have I ever tried oysters.',
    'Never have I ever eaten raw cookie dough.',
    'Never have I ever put ketchup on pasta.',
    'Never have I ever eaten peanut butter straight from the jar with a spoon.',
    'Never have I ever tried durian.',
    'Never have I ever eaten pineapple on pizza.',
    'Never have I ever burned a pot black.',
    'Never have I ever had chips for dinner.',
    'Never have I ever dipped fries in a milkshake.',
    'Never have I ever eaten soup straight from the pot.',
    'Never have I ever tried snails.',
    'Never have I ever followed a video recipe and made something completely different.',
    'Never have I ever eaten a whole chili pepper.',
    'Never have I ever eaten a sugar sandwich.',
    'Never have I ever cut the mold off bread and eaten the rest.',
    'Never have I ever gone back for thirds.',
    'Never have I ever eaten chocolate with chips.',
    'Never have I ever drunk milk straight from the carton.',
    'Never have I ever eaten standing at the open fridge at midnight.',
    'Never have I ever tried a dish without knowing what was in it.',
    'Never have I ever cooked a family recipe from memory.',
    'Never have I ever eaten ice cream outside in winter.',
    'Never have I ever eaten with my hands at a fancy restaurant.',
    'Never have I ever pretended to like a meal at someone’s house.',
    'Never have I ever ordered two desserts for myself.',
    'Never have I ever tried frog legs.',
    'Never have I ever eaten the same sandwich every day for a week.',
    'Never have I ever eaten a raw potato.',
    'Never have I ever ordered takeout three days in a row.',
    'Never have I ever eaten a whole watermelon in one sitting.',
    'Never have I ever put salt on watermelon.',
    'Never have I ever had breakfast at 4 p.m.',
    'Never have I ever eaten instant noodles dry.',
    'Never have I ever eaten cheese that smelled like feet.',
    'Never have I ever tried sushi.',
    'Never have I ever made a sandwich out of whatever was left in the fridge.',
    'Never have I ever had a hot dog for breakfast.',
    'Never have I ever finished a family-size bag of chips alone.',
  ],
} satisfies Deck
