import type { Deck } from '~/types'

export default {
  id: 'en-nhie-adventures',
  lang: 'en',
  type: 'never-have-i',
  title: 'Adventures',
  emoji: '🏕️',
  questions: [
    'Never have I ever slept in a tent.',
    'Never have I ever ridden a horse.',
    'Never have I ever driven more than ten hours in one day.',
    'Never have I ever swum in the ocean at night.',
    'Never have I ever slept in an airport.',
    'Never have I ever been in a helicopter.',
    'Never have I ever run a race longer than 5K.',
    'Never have I ever seen a shooting star.',
    'Never have I ever climbed a tree as an adult.',
    'Never have I ever ridden a rollercoaster three times in a row.',
    'Never have I ever built a snowman taller than me.',
    'Never have I ever milked a cow.',
    'Never have I ever been stuck in traffic for more than four hours.',
    'Never have I ever gone camping without a tent.',
    'Never have I ever hitchhiked.',
    'Never have I ever gone skiing or snowboarding.',
    'Never have I ever jumped off a cliff into water.',
    'Never have I ever been on a road trip with no destination.',
    'Never have I ever gotten lost in the woods.',
    'Never have I ever slept in a car overnight.',
    'Never have I ever taken a train ride longer than 24 hours.',
    'Never have I ever gone kayaking or canoeing.',
    'Never have I ever seen the northern lights.',
    'Never have I ever swum in a lake in winter.',
    'Never have I ever climbed a mountain above the clouds.',
    'Never have I ever gone zip-lining.',
    'Never have I ever flown in a hot air balloon.',
    'Never have I ever been scuba diving or snorkeling.',
    'Never have I ever ridden a camel or an elephant.',
    'Never have I ever cooked a meal over a campfire.',
    'Never have I ever been on a boat in a storm.',
    'Never have I ever explored a cave.',
    'Never have I ever missed a flight.',
    'Never have I ever gone fishing and actually caught something.',
    'Never have I ever walked barefoot in the snow.',
    'Never have I ever booked a trip the day before leaving.',
    'Never have I ever traveled alone to another country.',
    'Never have I ever slept on a beach.',
    'Never have I ever seen a bear in the wild.',
    'Never have I ever ridden a bike more than 30 miles in a day.',
    'Never have I ever pitched a tent in the dark.',
    'Never have I ever spent a whole trip without phone signal.',
    'Never have I ever been skydiving.',
    'Never have I ever drunk water straight from a stream.',
    'Never have I ever crossed a country border on foot.',
  ],
} satisfies Deck
