import type { Deck } from '~/types'

export default {
  id: 'en-nhie-little-sins',
  lang: 'en',
  type: 'never-have-i',
  title: 'Little Sins',
  emoji: '😇',
  questions: [
    'Never have I ever returned a gift for cash.',
    'Never have I ever gone a week without a shower.',
    'Never have I ever hidden a purchase from my family.',
    'Never have I ever spent a whole day in pajamas.',
    'Never have I ever slept through an alarm and missed something important.',
    'Never have I ever lied about my age.',
    'Never have I ever read the terms and conditions.',
    'Never have I ever called in sick when I wasn’t.',
    'Never have I ever borrowed someone’s charger without asking.',
    'Never have I ever fallen asleep with the TV on.',
    'Never have I ever binged a whole season in one night.',
    'Never have I ever skipped a concert I already had a ticket for.',
    'Never have I ever said “on my way” while still on the couch.',
    'Never have I ever hit snooze more than three times.',
    'Never have I ever pretended not to see a message.',
    'Never have I ever regifted a present.',
    'Never have I ever claimed to have read a book after only watching the movie.',
    'Never have I ever eaten someone else’s food from the office fridge.',
    'Never have I ever liked a post without reading it.',
    'Never have I ever said “I have to go” because I was bored.',
    'Never have I ever watched ahead on a show I was watching with someone.',
    'Never have I ever worn the same jeans for a week.',
    'Never have I ever turned off my camera on a call to go make tea.',
    'Never have I ever bought a gym membership and never gone.',
    'Never have I ever said “five minutes” and taken an hour.',
    'Never have I ever returned clothes after wearing them once.',
    'Never have I ever praised a gift I secretly hated.',
    'Never have I ever promised to start on Monday.',
    'Never have I ever taken the last cookie without asking.',
    'Never have I ever scrolled my phone at the dinner table.',
    'Never have I ever pretended to get a joke.',
    'Never have I ever hidden dirty dishes in the oven before guests arrived.',
    'Never have I ever peeked at someone’s phone over their shoulder.',
    'Never have I ever rated a delivery five stars without thinking.',
    'Never have I ever said “going to bed” and stayed up two more hours.',
    'Never have I ever nodded along without listening.',
    'Never have I ever used the same password everywhere.',
    'Never have I ever put my bag on the seat next to me on a full bus.',
    'Never have I ever bought something just because it was on sale and never used it.',
    'Never have I ever forgotten a friend’s birthday.',
    'Never have I ever declined a call from my mom and said “I’ll call back.”',
    'Never have I ever pretended to be asleep to avoid answering the door.',
    'Never have I ever put off laundry until I ran out of socks.',
    'Never have I ever unwrapped a present early and wrapped it back up.',
    'Never have I ever used a neighbor’s Wi-Fi without asking.',
  ],
} satisfies Deck
