import type { Deck } from '~/types'

export default {
  id: 'en-nhie-awkward',
  lang: 'en',
  type: 'never-have-i',
  title: 'Awkward Moments',
  emoji: '🙈',
  questions: [
    'Never have I ever sent a message to the wrong person.',
    'Never have I ever locked myself out of my own home.',
    'Never have I ever mumbled through a whole song pretending to know the words.',
    'Never have I ever forgotten someone’s name while introducing them.',
    'Never have I ever talked to myself out loud in public.',
    'Never have I ever walked into the wrong bathroom by accident.',
    'Never have I ever taken a selfie with a stranger.',
    'Never have I ever fallen asleep in a cinema.',
    'Never have I ever laughed so hard I couldn’t breathe.',
    'Never have I ever cried at a TV commercial.',
    'Never have I ever met someone famous.',
    'Never have I ever performed on a stage.',
    'Never have I ever been on a blind date.',
    'Never have I ever been to a wedding where I didn’t know the couple.',
    'Never have I ever cut my own hair.',
    'Never have I ever waved back at someone who was waving at someone else.',
    'Never have I ever been stuck in an elevator.',
    'Never have I ever said hello to a stranger I thought I knew.',
    'Never have I ever tripped in front of a crowd.',
    'Never have I ever called a teacher “Mom.”',
    'Never have I ever pushed a door that said “pull.”',
    'Never have I ever walked around all day with my shirt inside out.',
    'Never have I ever gotten into a stranger’s car thinking it was my ride.',
    'Never have I ever walked around for hours with spinach in my teeth.',
    'Never have I ever forgotten why I walked into a room.',
    'Never have I ever said “you too” when a waiter told me to enjoy my meal.',
    'Never have I ever taken the train in the wrong direction.',
    'Never have I ever worn mismatched shoes in public.',
    'Never have I ever laughed out loud in a silent room.',
    'Never have I ever called a friend by the wrong name.',
    'Never have I ever butt-dialed someone and stayed on the line.',
    'Never have I ever dropped my phone in the toilet.',
    'Never have I ever forgotten my own age when asked.',
    'Never have I ever missed my stop because I was daydreaming.',
    'Never have I ever clapped when nobody else did.',
    'Never have I ever shown up to a party on the wrong day.',
    'Never have I ever liked an old photo while scrolling someone’s profile.',
    'Never have I ever said goodbye and then walked the same way as the other person.',
    'Never have I ever sung out loud with headphones on in public.',
    'Never have I ever told someone a story they had told me first.',
    'Never have I ever gone in for a hug when someone offered a handshake.',
    'Never have I ever left the house in slippers by mistake.',
    'Never have I ever waved at my own reflection.',
    'Never have I ever replied “you too” to “happy birthday.”',
    'Never have I ever talked to a mannequin.',
  ],
} satisfies Deck
