import type { Deck } from '~/types'

export default {
  id: 'en-silly-dilemmas',
  lang: 'en',
  type: 'would-you-rather',
  title: 'Silly Dilemmas',
  emoji: '🤪',
  questions: [
    'Would you rather have hiccups forever or always feel like you’re about to sneeze?',
    'Would you rather fight one horse-sized duck or a hundred duck-sized horses?',
    'Would you rather have a permanent unibrow or permanently wet hands?',
    'Would you rather speak only in rhymes or only in questions?',
    'Would you rather have fingers as long as legs or legs as short as fingers?',
    'Would you rather sweat maple syrup or cry glitter?',
    'Would you rather have every song stuck in your head or never remember a single lyric?',
    'Would you rather have a theme song play when you enter a room or a laugh track?',
    'Would you rather wear a wetsuit to every meeting or a tuxedo to every beach?',
    'Would you rather be followed by a mariachi band or a cloud that rains only on you?',
    'Would you rather get a nose that grows when you lie or ears that flap when you’re nervous?',
    'Would you rather only ever walk backwards or only ever sit on the floor?',
    'Would you rather have pockets full of sand forever or shoes always one size too small?',
    'Would you rather talk to animals that are all rude or to plants that only gossip?',
    'Would you rather eat a spoonful of wasabi or bite into a raw onion like an apple?',
    'Would you rather sound like a cartoon chipmunk or a movie-trailer narrator forever?',
    'Would you rather have a beard of bees or a hat made of live snails?',
    'Would you rather have to hop everywhere or crawl everywhere?',
    'Would you rather have mood-colored hair or teeth that glow in the dark?',
    'Would you rather live in a house made of cheese or a house made of Lego?',
    'Would you rather announce every thought out loud or never be able to speak indoors?',
    'Would you rather get tickled when someone says your name or sneeze when someone says hi?',
    'Would you rather have a pet dinosaur the size of a cat or a cat the size of a dinosaur?',
    'Would you rather only eat foods that are blue or only foods that crunch?',
    'Would you rather share a tiny tent with a mime or with a clown who won’t stop honking?',
    'Would you rather wear roller skates everywhere or oven mitts everywhere?',
    'Would you rather have a voice only dogs can hear or a face only babies find funny?',
    'Would you rather squeak like a rubber duck when you sit or honk when you stand up?',
    'Would you rather sing everything you say in a shop or dance whenever a phone rings?',
    'Would you rather have a third arm on your back or a second mouth on your hand?',
    'Would you rather high-five everyone you meet or bow deeply to every dog?',
    'Would you rather have a permanent pirate accent or permanently talk like a robot?',
    'Would you rather have jelly for bones for a day or rocks for feet for a week?',
    'Would you rather have a nose on your knee or an eye on your elbow?',
    'Would you rather wear a full chicken costume for a week or clown shoes for a year?',
    'Would you rather have bread for hands or butter for feet?',
    'Would you rather always have a tiny pebble in your shoe or a hair in every meal?',
    'Would you rather laugh like a goat or cry like a car alarm?',
    'Would you rather be a giant hamster or a tiny elephant?',
    'Would you rather ride a unicycle to work or a pogo stick to the shops?',
    'Would you rather have a tail that wags when you’re happy or ears that droop when sad?',
    'Would you rather have a mustache that grows an inch a day or eyebrows that wiggle nonstop?',
    'Would you rather have a doorbell that plays your singing or a phone that reads your texts?',
    'Would you rather wear socks on your hands or gloves on your feet all day?',
  ],
} satisfies Deck
