import type { Deck } from '~/types'

export default {
  id: 'en-travel',
  lang: 'en',
  type: 'most-likely',
  title: 'Travel & Adventure',
  emoji: '🧭',
  questions: [
    'Who’s most likely to pack three outfits per day for a weekend trip?',
    'Who’s most likely to arrive at the airport four hours early and still panic?',
    'Who’s most likely to miss a flight while sitting right at the gate?',
    'Who’s most likely to learn five words of a language and use them constantly?',
    'Who’s most likely to make friends with the whole hostel by breakfast?',
    'Who’s most likely to take 400 photos of the same sunset?',
    'Who’s most likely to pick a restaurant by the length of the line?',
    'Who’s most likely to sleep through an entire road trip in the back seat?',
    'Who’s most likely to get sunburned on a cloudy day?',
    'Who’s most likely to plan an itinerary down to the minute?',
    'Who’s most likely to land in a new country with no plan and no hotel?',
    'Who’s most likely to try a mystery street food and love it?',
    'Who’s most likely to pack a first-aid kit for a trip to the mall?',
    'Who’s most likely to take a wrong turn and find the best spot of the trip?',
    'Who’s most likely to spend the whole beach day in the shade with a book?',
    'Who’s most likely to forget their passport and remember it at the check-in desk?',
    'Who’s most likely to haggle at a market and end up paying more?',
    'Who’s most likely to be the navigator and argue with the map?',
    'Who’s most likely to go camping and bring an espresso machine?',
    'Who’s most likely to cry at the top of a mountain?',
    'Who’s most likely to get on the wrong train and end up in the wrong city?',
    'Who’s most likely to fill the whole suitcase with souvenirs for other people?',
    'Who’s most likely to swim in a freezing lake on a dare?',
    'Who’s most likely to fall asleep on a night bus and wake up two towns too late?',
    'Who’s most likely to try the local dish once and eat pizza every night after?',
    'Who’s most likely to pitch a tent in the dark with the manual upside down?',
    'Who’s most likely to get lost in a museum and end up in the staff room?',
    'Who’s most likely to become best friends with a taxi driver in ten minutes?',
    'Who’s most likely to sign up for a bungee jump and back out at the edge?',
    'Who’s most likely to pick a destination by spinning a globe?',
    'Who’s most likely to pack a full pharmacy and forget a toothbrush?',
    'Who’s most likely to hike ten miles for a view and stare at their phone at the top?',
    'Who’s most likely to lock the keys inside the rental car?',
    'Who’s most likely to live off the hotel breakfast buffet to save money?',
    'Who’s most likely to have sand in the car six months after one beach day?',
    'Who’s most likely to reread the hotel reviews every hour before check-in?',
    'Who’s most likely to walk 30,000 steps and call it a rest day?',
    'Who’s most likely to befriend a stray cat on every trip?',
    'Who’s most likely to volunteer for the scary bridge and regret it halfway across?',
    'Who’s most likely to blow the whole trip budget on the first day?',
    'Who’s most likely to be greeted by name at their favorite hostel?',
    'Who’s most likely to get seasick on a lake?',
    'Who’s most likely to stretch a weekend trip into a month?',
    'Who’s most likely to bring a travel pillow and never once use it?',
  ],
} satisfies Deck
