import type { Deck } from '~/types'

export default {
  id: 'en-warm-up',
  lang: 'en',
  type: 'most-likely',
  title: 'Warm-up',
  emoji: '🔥',
  questions: [
    'Who’s most likely to talk their way out of a parking ticket?',
    'Who’s most likely to cry at a stranger’s wedding?',
    'Who’s most likely to become a millionaire by accident?',
    'Who’s most likely to get lost with GPS on?',
    'Who’s most likely to fall asleep at a concert?',
    'Who’s most likely to name their kid after a TV character?',
    'Who’s most likely to laugh at their own joke before the punchline?',
    'Who’s most likely to forget their own birthday?',
    'Who’s most likely to survive a zombie apocalypse?',
    'Who’s most likely to start a band at forty?',
    'Who’s most likely to get talked into anything by a toddler?',
    'Who’s most likely to quit their job on a whim?',
    'Who’s most likely to become famous for something embarrassing?',
    'Who’s most likely to trip on a perfectly flat surface?',
    'Who’s most likely to eat cereal for dinner three nights in a row?',
    'Who’s most likely to book a flight at 2 a.m. and actually go?',
    'Who’s most likely to lose their keys while holding them?',
    'Who’s most likely to know every word of a song from twenty years ago?',
    'Who’s most likely to talk to their plants?',
    'Who’s most likely to go to bed at 9 p.m. on a Friday?',
    'Who’s most likely to fake a phone call to escape a conversation?',
    'Who’s most likely to own a gadget they’ve never taken out of the box?',
    'Who’s most likely to still be partying at ninety?',
    'Who’s most likely to become a reality TV star?',
    'Who’s most likely to bring a board game to a nightclub?',
    'Who’s most likely to sing karaoke completely sober?',
    'Who’s most likely to get stuck in an elevator and enjoy it?',
    'Who’s most likely to befriend the neighbors’ dog before the neighbors?',
    'Who’s most likely to invent a holiday just to celebrate it?',
    'Who’s most likely to google their own name?',
    'Who’s most likely to walk into a glass door?',
    'Who’s most likely to cancel plans to stay in bed?',
    'Who’s most likely to volunteer to go first at anything?',
    'Who’s most likely to lose a bet and actually pay up?',
    'Who’s most likely to have a secret talent nobody knows about?',
    'Who’s most likely to have 3,000 unread emails?',
    'Who’s most likely to accidentally like a five-year-old photo while snooping?',
    'Who’s most likely to be the last one standing at a party?',
    'Who’s most likely to join a gym and go exactly once?',
    'Who’s most likely to dye their hair a wild color tomorrow?',
    'Who’s most likely to leave a party with three new best friends?',
    'Who’s most likely to narrate their life like a nature documentary?',
    'Who’s most likely to lose a staring contest to a cat?',
    'Who’s most likely to reorganize someone else’s kitchen without asking?',
    'Who’s most likely to wear sunglasses indoors?',
    'Who’s most likely to cheat at a board game and deny it?',
    'Who’s most likely to take a two-hour nap and call it a quick rest?',
    'Who’s most likely to start a podcast nobody asked for?',
  ],
} satisfies Deck
