import type { Deck } from '~/types'

export default {
  id: 'en-what-if',
  lang: 'en',
  type: 'would-you-rather',
  title: 'What If',
  emoji: '🪄',
  questions: [
    'Would you rather be able to fly or be invisible?',
    'Would you rather pause time or rewind it ten seconds?',
    'Would you rather live in the world of your favorite book or your favorite video game?',
    'Would you rather have a dragon or be a dragon?',
    'Would you rather speak every language or play every instrument?',
    'Would you rather have a teleport button for once a day or a jet that’s always ready?',
    'Would you rather live a hundred years in the past or a hundred years in the future?',
    'Would you rather have a robot that does your chores or one that does your job?',
    'Would you rather be able to talk to animals or read minds?',
    'Would you rather never need sleep or never need food?',
    'Would you rather have a house that cleans itself or a car that drives itself?',
    'Would you rather have a map to any lost treasure or a key to any door?',
    'Would you rather relive one day of your life or see one day of your future?',
    'Would you rather win the lottery or stumble into your dream job?',
    'Would you rather have a lifetime supply of your favorite food or free travel forever?',
    'Would you rather be the best in the world at one thing or pretty good at everything?',
    'Would you rather have a photographic memory or the power to forget anything on demand?',
    'Would you rather shrink to the size of a mouse for a day or grow to the size of a house?',
    'Would you rather have an extra hour every day or an extra day every week?',
    'Would you rather swap lives with a celebrity for a week or with your pet?',
    'Would you rather be able to breathe underwater or survive in space?',
    'Would you rather have a backpack that holds anything or a wallet that never runs out?',
    'Would you rather live on a cloud or under the sea?',
    'Would you rather have a superpower nobody knows about or fame for something you didn’t do?',
    'Would you rather never lose an argument or never lose anything?',
    'Would you rather see ten minutes into the future or, just once, ten years?',
    'Would you rather have a clone for boring events or a twin who does your workouts?',
    'Would you rather control the weather or control traffic?',
    'Would you rather get a free house anywhere in the world or free tickets anywhere, forever?',
    'Would you rather be a wizard in a world without magic or ordinary in a world full of it?',
    'Would you rather have your dreams come true every night or never dream at all?',
    'Would you rather be able to taste colors or see music?',
    'Would you rather wake up fluent in an animal language or in an ancient one?',
    'Would you rather have a pen that writes only truth or a phone that gets only good news?',
    'Would you rather be twenty forever or wise beyond your years right now?',
    'Would you rather have a personal chef or a personal driver?',
    'Would you rather get one wish now or three wishes in ten years?',
    'Would you rather redo any one decision or skip any one bad day?',
    'Would you rather own a library with every book ever or a cinema with every film ever?',
    'Would you rather be a famous inventor or a famous explorer?',
    'Would you rather spend a day on the Moon or at the bottom of the ocean?',
    'Would you rather have a talking car or a flying bike?',
    'Would you rather learn any skill instantly once a year or learn everything twice as fast?',
    'Would you rather live in a treehouse or a lighthouse?',
    'Would you rather find out aliens exist or that time travel is real?',
  ],
} satisfies Deck
