import type { ThemeId } from '~/types'

/** Spy words in English: singular, capitalized, ≤ 24 characters. */
export default {
  places: [
    'School',
    'Kindergarten',
    'Hospital',
    'Airport',
    'Train station',
    'Beach',
    'Zoo',
    'Circus',
    'Movie theater',
    'Library',
    'Museum',
    'Supermarket',
    'Bakery',
    'Hair salon',
    'Restaurant',
    'Fire station',
    'Police station',
    'Swimming pool',
    'Ice rink',
    'Stadium',
    'Playground',
    'Amusement park',
    'Farm',
    'Campsite',
    'Castle',
    'Pirate ship',
    'Submarine',
    'Space station',
  ],
  animals: [
    'Cat',
    'Dog',
    'Cow',
    'Horse',
    'Pig',
    'Sheep',
    'Goat',
    'Rabbit',
    'Hamster',
    'Parrot',
    'Lion',
    'Tiger',
    'Elephant',
    'Giraffe',
    'Zebra',
    'Monkey',
    'Bear',
    'Wolf',
    'Fox',
    'Squirrel',
    'Hedgehog',
    'Crocodile',
    'Penguin',
    'Kangaroo',
    'Dolphin',
    'Shark',
    'Turtle',
    'Camel',
    'Owl',
    'Panda',
  ],
  professions: [
    'Doctor',
    'Nurse',
    'Teacher',
    'Chef',
    'Firefighter',
    'Police officer',
    'Bus driver',
    'Pilot',
    'Astronaut',
    'Builder',
    'Cashier',
    'Hairdresser',
    'Mail carrier',
    'Artist',
    'Musician',
    'Singer',
    'Actor',
    'Photographer',
    'Vet',
    'Farmer',
    'Programmer',
    'Baker',
    'Dentist',
    'Sailor',
    'Gardener',
    'Librarian',
    'Clown',
    'Coach',
  ],
  countries: [
    'United States',
    'Canada',
    'Mexico',
    'Brazil',
    'Argentina',
    'United Kingdom',
    'Ireland',
    'France',
    'Germany',
    'Italy',
    'Spain',
    'Greece',
    'Egypt',
    'South Africa',
    'Kenya',
    'India',
    'China',
    'Japan',
    'South Korea',
    'Thailand',
    'Australia',
    'New Zealand',
    'Russia',
    'Norway',
    'Sweden',
    'Switzerland',
    'Netherlands',
    'Jamaica',
  ],
  cities: [
    'New York',
    'Los Angeles',
    'Las Vegas',
    'San Francisco',
    'Chicago',
    'Miami',
    'Toronto',
    'London',
    'Edinburgh',
    'Dublin',
    'Paris',
    'Rome',
    'Venice',
    'Barcelona',
    'Madrid',
    'Berlin',
    'Amsterdam',
    'Athens',
    'Moscow',
    'Istanbul',
    'Dubai',
    'Cairo',
    'Tokyo',
    'Beijing',
    'Hong Kong',
    'Sydney',
    'Rio de Janeiro',
  ],
  sports: [
    'Soccer',
    'American football',
    'Basketball',
    'Baseball',
    'Ice hockey',
    'Volleyball',
    'Tennis',
    'Table tennis',
    'Badminton',
    'Swimming',
    'Boxing',
    'Karate',
    'Wrestling',
    'Gymnastics',
    'Figure skating',
    'Skiing',
    'Snowboarding',
    'Skateboarding',
    'Surfing',
    'Golf',
    'Cycling',
    'Running',
    'Fencing',
    'Rock climbing',
    'Horse riding',
    'Archery',
    'Bowling',
  ],
  'fairy-tales': [
    'Cinderella',
    'Snow White',
    'Sleeping Beauty',
    'Rapunzel',
    'Little Red Riding Hood',
    'Big Bad Wolf',
    'Goldilocks',
    'Gingerbread Man',
    'Humpty Dumpty',
    'Rumpelstiltskin',
    'Frog Prince',
    'Fairy Godmother',
    'Evil Queen',
    'Puss in Boots',
    'Tom Thumb',
    'Thumbelina',
    'Little Mermaid',
    'Snow Queen',
    'Ugly Duckling',
    'Nutcracker',
    'Pinocchio',
    'Peter Pan',
    'Tinker Bell',
    'Captain Hook',
    'Alice',
    'Mad Hatter',
    'Cheshire Cat',
    'Dorothy',
    'Robin Hood',
    'Aladdin',
  ],
  cartoons: [
    'Mickey Mouse',
    'Minnie Mouse',
    'Donald Duck',
    'Goofy',
    'Bugs Bunny',
    'Scooby-Doo',
    'SpongeBob',
    'Patrick Star',
    'Shrek',
    'Simba',
    'Nemo',
    'Dory',
    'Woody',
    'Buzz Lightyear',
    'Lightning McQueen',
    'Elsa',
    'Olaf',
    'Winnie the Pooh',
    'Piglet',
    'Peppa Pig',
    'Jerry',
    'Pikachu',
    'Minion',
    'Bluey',
    'Stitch',
    'Moana',
    'Kung Fu Panda',
    'Snoopy',
  ],
  superheroes: [
    'Batman',
    'Superman',
    'Spider-Man',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Thor',
    'Black Widow',
    'Wonder Woman',
    'Flash',
    'Aquaman',
    'Black Panther',
    'Doctor Strange',
    'Ant-Man',
    'Captain Marvel',
    'Groot',
    'Shazam',
    'Hawkeye',
    'Loki',
    'Joker',
    'Thanos',
    'Venom',
    'Green Goblin',
    'Doctor Octopus',
    'Magneto',
    'Catwoman',
    'Lex Luthor',
  ],
  home: [
    'Table',
    'Chair',
    'Sofa',
    'Bed',
    'Closet',
    'Fridge',
    'TV',
    'Lamp',
    'Mirror',
    'Pillow',
    'Blanket',
    'Rug',
    'Toaster',
    'Frying pan',
    'Plate',
    'Spoon',
    'Fork',
    'Mug',
    'Iron',
    'Vacuum cleaner',
    'Washing machine',
    'Microwave',
    'Toothbrush',
    'Towel',
    'Soap',
    'Bathtub',
    'Curtain',
    'Clock',
  ],
} satisfies Partial<Record<ThemeId, string[]>>
